#!/bin/bash

PACKAGE_JS="package.js"

SASS_FILES=`find . \( -name "*.scss" -or -name "*.sass" \) | sed "s|^\./||"`

# remove everything after the token
sed -i '' '/AUTOGENERATED/,$d' $PACKAGE_JS
echo "  // AUTOGENERATED" >> $PACKAGE_JS

# add all sass/scss files
echo "  api.addFiles([" >> $PACKAGE_JS
for FILE in $SASS_FILES
do
  echo "    '$FILE'," >> $PACKAGE_JS
done
echo "  ], 'server', {isAsset:true});" >> $PACKAGE_JS

# end the use statement
echo "});" >> $PACKAGE_JS
