#!/bin/bash

PACKAGE_JS="package.js"

SASS_FILES=`find . \( -name "*.scss" -or -name "*.sass" \) | sed "s|^\./||"`
HTML_FILES=`find . -name "*.html" | sed "s|^\./||"`
COFFEE_FILES=`find . -name "*.coffee" | sed "s|^\./||"`

# remove everything after the token
sed -i '' '/AUTOGENERATED/,$d' $PACKAGE_JS
echo "  // AUTOGENERATED" >> $PACKAGE_JS

# add all sass/scss files
echo "  api.addFiles([" >> $PACKAGE_JS
for FILE in $SASS_FILES
do
  echo "    '$FILE'," >> $PACKAGE_JS
done
echo "  ], 'server', {isAsset:true});" >> $PACKAGE_JS

echo "" >> $PACKAGE_JS
echo "" >> $PACKAGE_JS
echo " // AUTOGENERATED HTML and CoffeeScript Template Files //" >> $PACKAGE_JS
echo "" >> $PACKAGE_JS
echo "" >> $PACKAGE_JS

# add all html and coffeescript files
echo "  api.addFiles([" >> $PACKAGE_JS
for FILE in $HTML_FILES
do
  echo "    '$FILE'," >> $PACKAGE_JS
done
echo "" >> $PACKAGE_JS
for FILE in $COFFEE_FILES
do
  echo "    '$FILE'," >> $PACKAGE_JS
done
echo "  ], 'client');" >> $PACKAGE_JS

# end the use statement
echo "});" >> $PACKAGE_JS
