Package.describe({
  name: 'getoutfitted:reaction-foundation-theme',
  version: '0.0.1',
  summary: 'Zurb Foundation 5 starter theme for ReactionCommerce',
  git: 'https://github.com/getoutfitted/reaction-foundation-theme.git'
});

Package.onUse(function (api) {
    api.versionsFrom('METEOR@1.0');
    api.imply('fourseven:scss@2.0.1_2');
	api.use([
		'jquery@1.0.0',
		'fourseven:scss@2.0.1_2',
	], 'client');

	api.addFiles([
    'js/vendor/modernizr.js',
    'js/foundation.js'
	], 'client');

  // Everything after this point is generated by the build-package.sh
  // AUTOGENERATED
  api.addFiles([
    'scss/foundation/_functions.scss',
    'scss/foundation/_settings.scss',
    'scss/foundation/components/_accordion.scss',
    'scss/foundation/components/_alert-boxes.scss',
    'scss/foundation/components/_block-grid.scss',
    'scss/foundation/components/_breadcrumbs.scss',
    'scss/foundation/components/_button-groups.scss',
    'scss/foundation/components/_buttons.scss',
    'scss/foundation/components/_clearing.scss',
    'scss/foundation/components/_dropdown-buttons.scss',
    'scss/foundation/components/_dropdown.scss',
    'scss/foundation/components/_flex-video.scss',
    'scss/foundation/components/_forms.scss',
    'scss/foundation/components/_global.scss',
    'scss/foundation/components/_grid.scss',
    'scss/foundation/components/_icon-bar.scss',
    'scss/foundation/components/_iconbar.scss',
    'scss/foundation/components/_inline-lists.scss',
    'scss/foundation/components/_joyride.scss',
    'scss/foundation/components/_keystrokes.scss',
    'scss/foundation/components/_labels.scss',
    'scss/foundation/components/_magellan.scss',
    'scss/foundation/components/_offcanvas.scss',
    'scss/foundation/components/_orbit.scss',
    'scss/foundation/components/_pagination.scss',
    'scss/foundation/components/_panels.scss',
    'scss/foundation/components/_pricing-tables.scss',
    'scss/foundation/components/_progress-bars.scss',
    'scss/foundation/components/_range-slider.scss',
    'scss/foundation/components/_reveal-new.scss',
    'scss/foundation/components/_reveal.scss',
    'scss/foundation/components/_side-nav.scss',
    'scss/foundation/components/_split-buttons.scss',
    'scss/foundation/components/_sub-nav.scss',
    'scss/foundation/components/_switch.scss',
    'scss/foundation/components/_switches.scss',
    'scss/foundation/components/_tables.scss',
    'scss/foundation/components/_tabs.scss',
    'scss/foundation/components/_thumbs.scss',
    'scss/foundation/components/_toolbar.scss',
    'scss/foundation/components/_tooltips.scss',
    'scss/foundation/components/_top-bar.scss',
    'scss/foundation/components/_type.scss',
    'scss/foundation/components/_visibility.scss',
    'scss/foundation/components/_xy-center.scss',
    'scss/foundation.scss',
    'scss/normalize.scss',
  ], 'server', {isAsset:true});
});
